#!/usr/bin/env bash

# Catppuccin mocha color palette
black="0xff45475A"
red="0xffF38BA8"
green="0xffA6E3A1"
yellow="0xffF9E2AF"
blue="0xff89B4FA"
magenta="0xffF5C2E7"
cyan="0xff94E2D5"
white="0xffBAC2DE"
transparent="0x00000000"

bright_black="0xff585b70"
bright_red="0xfff38ba8"
bright_green="0xffa6e3a1"
bright_yellow="0xfff9e2af"
bright_blue="0xff89b4fa"
bright_magenta="0xfff5c2e7"
bright_cyan="0xff94e2d5"
bright_white="0xffa6adc8"

dim_black="0xff45475A"
dim_red="0xffF38BA8"
dim_green="0xffA6E3A1"
dim_yellow="0xffF9E2AF"
dim_blue="0xff89B4FA"
dim_magenta="0xffF5C2E7"
dim_cyan="0xff94E2D5"
dim_white="0xffBAC2DE"

# Bar
## Colors
BAR_COLOR="$transparent"
BAR_BLUR_RADIUS=30

## Geometry
BAR_POSITION="top"
BAR_HEIGHT=24
BAR_PADDING=0
BAR_Y_OFFSET=8
BAR_CORNER_RADIUS=12
BAR_MARGIN=10

# Item Defaults
## Colors
BACKGROUND_COLOR="$black"
BACKGROUND_BORDER_COLOR="$blue"
BACKGROUND_BORDER_WIDTH=0
LABEL_ALIGN="center"
LABEL_COLOR="$blue"
LABEL_HIGHLIGHT_COLOR="$red"

## Fonts
ICON_BASE_FONT="Hack Nerd Font"
ICON_FONT="$ICON_BASE_FONT:Bold:14.0"
LABEL_BASE_FONT="Hack Nerd Font"
LABEL_FONT="$LABEL_BASE_FONT:Regular:14.0"
LABEL_HIGHLIGHT_FONT="$LABEL_BASE_FONT:Regular:14.0"

## Geometry
BACKGROUND_CORNER_RADIUS=4
BACKGROUND_HEIGHT=24
LABEL_Y_OFFSET=1
LABEL_PADDING=6
BRACKET_BACKGROUND_BORDER_WIDTH=2
BRACKET_BACKGROUND_CORNER_RADIUS=12
