[font]
size=8.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

# we don't need window title
[window]
decorations = "none"
