[font]
size=12.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[window]
decorations = "none"
option_as_alt = "Both"
opacity = 0.8
blur = true

[terminal.shell]
program = "/bin/zsh"
args = [
  "--login",
  "-c",
  "tmux attach || tmux new-session -s default"
]

# [keyboard]
# bindings = [
# { key = "Tab", mods = "Control", action = "ReceiveChar" },
# { key = "q", mods = "Alt", action = "Quit" }
# ]
