#!/usr/bin/env zsh

function random-session () {
  adjectives=("valuable" "modern" "wasteful" "three" "nice" "acidic" "abstracted" "mindless" "frantic" "voracious" "marvelous" "tawdry" "confused" "moldy" "useful" "alert" "neighborly" "cuddly" "lovely" "glossy" "mellow" "tightfisted" "tested" "clever" "false" "alleged" "far" "thirsty" "subsequent" "unusual" "macabre" "unequaled" "spotless" "honorable" "long-term" "heady" "imperfect" "nauseating" "scary" "quack" "lyrical" "auspicious" "spectacular" "dull" "natural" "brief" "far-flung" "new" "yummy" "equal" "shiny" "warm" "calculating" "closed" "needy" "proud" "wrathful" "open" "tough" "meek" "narrow" "hanging" "obese" "giant" "pathetic" "volatile" "spiky" "strong" "grieving" "chemical" "clumsy" "gaping" "heartbreaking" "loose" "solid" "envious" "workable" "kaput" "flimsy" "awake" "watery" "jittery" "unarmed" "high" "accessible" "maddening" "wretched" "condemned" "inexpensive" "rotten" "wild" "bright" "productive" "careless" "scared" "shrill" "thick" "nasty" "internal" "zippy" "soggy" "sloppy" "calm" "real" "awful" "flawless" "reminiscent" "utopian" "rustic" "nondescript" "arrogant" "mute" "unkempt" "daffy" "shaky" "spooky" "energetic" "red" "better" "angry" "fluttering" "comfortable" "disillusioned" "wiggly" "second" "nosy" "selfish" "kindhearted" "uttermost" "trashy" "spurious" "ceaseless" "holistic" "mountainous" "parched" "late" "accidental" "versed" "unsightly" "vengeful" "scientific" "tense" "black-and-white" "secretive" "damp" "chunky" "fluffy" "brave" "icy" "high-pitched" "godly" "deafening" "dizzy" "weak" "puzzling" "sassy" "exultant" "resonant" "awesome" "distinct" "terrific" "elite" "silky" "furry" "foolish" "understood" "dry" "curvy" "hapless" "pretty" "marked" "smelly" "quarrelsome" "peaceful" "poor" "invincible" "cute" "shy" "offbeat" "sore" "shallow" "questionable" "tart" "tall" "tasteful" "devilish" "embarrassed" "idiotic" "tangible" "famous" "imported" "plastic" "shaggy" "numberless" "well-made" "splendid" "decisive" "normal" "majestic" "superb")
  animals=("pig" "mule" "sheep" "orangutan" "okapi" "capybara" "bighorn" "springbok" "sloth" "frog" "duckbill platypus" "basilisk" "quagga" "seal" "jackal" "salamander" "ox" "elephant" "argali" "aoudad" "silver fox" "chimpanzee" "bear" "alligator" "chicken" "jerboa" "hyena" "doe" "kangaroo" "iguana" "alpaca" "guinea pig" "llama" "turtle" "rooster" "pony" "bull" "lamb" "chinchilla" "koala" "mustang" "cow" "zebu" "mynah bird" "lemur" "mare" "eagle owl" "moose" "lizard" "chipmunk" "cat" "gemsbok" "whale" "buffalo" "hare" "toad" "dugong" "bat" "armadillo" "horse" "leopard" "panda" "ape" "warthog" "woodchuck" "prairie dog" "tiger" "coyote" "mouse" "starfish" "tapir" "elk" "marten" "dormouse" "panther" "mountain goat" "mole" "ermine" "hippopotamus" "donkey" "hedgehog" "beaver" "hog" "thorny devil" "monkey" "bald eagle" "stallion" "parakeet" "aardvark" "coati" "ocelot" "polar bear" "mink" "puma" "shrew" "otter" "skunk" "deer" "kitten" "bumble bee" "lovebird" "squirrel" "dung beetle" "badger" "eland" "cougar" "addax" "raccoon" "ewe" "mongoose" "oryx" "burro" "porcupine" "ferret" "finch" "peccary" "hartebeest" "rabbit" "bison" "meerkat" "puppy" "jaguar" "vicuna" "boar" "anteater" "cheetah" "rat" "parrot" "yak" "snake" "opossum" "walrus" "musk deer" "gnu" "porpoise" "newt" "blue crab" "weasel" "gila monster" "antelope" "hamster" "colt" "grizzly bear" "musk-ox" "camel" "fox" "wombat" "crow" "mandrill" "muskrat" "dromedary" "zebra" "civet" "wolf" "dog" "gorilla" "gazelle" "dingo" "chamois" "ground hog" "lion" "budgerigar" "gopher" "highland cow" "rhinoceros" "ram" "steer" "baboon" "fawn" "canary" "snowy owl" "guanaco" "pronghorn" "reindeer" "impala" "marmoset" "wildcat" "ibex" "fish" "lynx" "bunny" "crocodile" "wolverine" "giraffe" "goat" "waterbuck" "octopus" "chameleon")

  adjectiveIndex="$((0 + $RANDOM % 199))"
  animalIndex="$((0 + $RANDOM % 187))"
  adjective="${adjectives[$adjectiveIndex]}"
  animal="${animals[$animalIndex]}"

  echo "$adjective-$animal" | sed -e 's/\ /-/g'
}
function t () {
  tmux attach || tmux new -s $(random-session)
}
function random-rename-current-tmux-session () {
  tmux rename -t $(tmux display-message -p '#S') $(random-session)
}
