[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "quit"
desc = "Quits yazi"
