#!/bin/bash

source ./scripts/utils

echo "Setting up snapper..."

must_be_root

if snapper -c root get-config; then
  echo "Snapper config exists, exiting"
  exit
fi

snapper -c root create-config /

/etc/grub.d/41_snapshots-btrfs
grub-mkconfig -o /boot/grub/grub.cfg

systemctl start grub-btrfsd
systemctl enable grub-btrfsd

is_service_running grub-btrfsd
