#!/bin/bash

function draw_line() {
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
}

function must_be_root() {
  if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
  fi
}

function must_not_be_root() {
  if [ "$EUID" -eq 0 ]; then
    echo "Please DO NOT run as root"
    exit 1
  fi
}

function is_service_running() {
  if systemctl is-active --quiet $1; then
    echo "$1 is running :)"
  else
    echo "ERROR: $1 is NOT running"
    systemctl status $1
    exit 1
  fi
}
