-- FzfLua
local FzfLua = require("fzf-lua")
vim.keymap.set("n", "<leader>sr", function()
  FzfLua.oldfiles()
end)
vim.keymap.set("n", "<leader>sf", function()
  FzfLua.files()
end)
vim.keymap.set("n", "<leader>st", function()
  FzfLua.live_grep()
end)
vim.keymap.set("n", "<leader>sz", function()
  FzfLua.zoxide()
end)
vim.keymap.set("n", "<leader>sw", function()
  FzfLua.grep_cWORD()
end)
vim.keymap.set("n", "<leader>sh", function()
  FzfLua.helptags()
end)
vim.keymap.set("n", "<leader>sj", function()
  FzfLua.jumps()
end)
vim.keymap.set("n", "<leader>e", ":Neotree toggle float<CR>")
vim.keymap.set("n", "<leader>E", ":NeoTreeFloatCurrentDir<CR>")
vim.keymap.set({ "n", "v", "i" }, "<C-x>", ":bd<CR>", { silent = true })

-- editing
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<S-down>", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "<S-up>", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "<S-left>", "<gv")
vim.keymap.set("v", "<S-right>", ">gv")
vim.keymap.set({ "n", "v" }, "c", '"_c')
vim.keymap.set({ "n", "v" }, "C", '"_C')
vim.keymap.set("v", "p", "P")
vim.keymap.set("n", "<leader>F", function()
  require("conform").format()
end)
vim.keymap.set("n", "<leader>f", "<cmd>ConformToggle<CR>", { desc = "Toggle autoformatting" })

-- windows
vim.keymap.set({ "n", "v", "i" }, "<c-v>", ":vsplit<CR>")
vim.keymap.set({ "n", "v", "i" }, "<c-down>", "<c-w>j")
vim.keymap.set({ "n", "v", "i" }, "<c-up>", "<c-w>k")
vim.keymap.set({ "n", "v", "i" }, "<c-right>", "<c-w>l")
vim.keymap.set({ "n", "v", "i" }, "<c-left>", "<c-w>h")

-- buffers
vim.keymap.set("n", "<leader>bo", ":%bd|e#|bd#<CR>", { silent = true }) -- close all buffers but the current one
vim.keymap.set({ "n", "v", "i" }, "<C-x>", ":bd<CR>", { silent = true })
vim.keymap.set("n", "<leader>by", ":%y<CR>")
vim.keymap.set("n", "<leader>bY", ":let @+ = expand('%:p')", { silent = true })
vim.keymap.set("n", "<Tab>", "<C-S-^>")
vim.keymap.set("n", "<S-Tab>", ":bprevious<CR>", { silent = true })
vim.keymap.set("n", "<C-Tab>", ":bnext<CR>", { silent = true })
vim.keymap.set("n", "<C-S-Tab>", ":bprevious<CR>", { silent = true })
vim.keymap.set("n", "<Esc>", ":noh<CR>")

vim.keymap.set("n", "<leader>gg", ":LazyGit<CR>")

vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "<Down>", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("n", "<Up>", "gk")
