-- FzfLua
local FzfLua = require("fzf-lua")
vim.keymap.set("n", "<leader>sd", function()
  FzfLua.diagnostics_document()
end)
vim.keymap.set("n", "<leader>sb", function()
  FzfLua.buffers()
end)
vim.keymap.set("n", "<leader>sr", function()
  FzfLua.oldfiles()
end)
vim.keymap.set("n", "<leader>sf", function()
  FzfLua.files()
end)
vim.keymap.set("n", "<leader>st", function()
  FzfLua.live_grep()
end)
vim.keymap.set("n", "<leader>sz", function()
  FzfLua.zoxide()
end)
vim.keymap.set("n", "<leader>sw", function()
  FzfLua.grep_cWORD()
end)
vim.keymap.set("n", "<leader>sh", function()
  FzfLua.helptags()
end)
vim.keymap.set("n", "<leader>sj", function()
  FzfLua.jumps()
end)
vim.keymap.set("n", "<leader>sm", function()
  FzfLua.marks()
end)
vim.keymap.set("n", "<leader><leader>", function()
  FzfLua.buffers()
end)
vim.keymap.set("n", "<leader>e", ":Oil<CR>", { silent = true })
vim.keymap.set({ "n", "v", "i" }, "<C-x>", ":bd<CR>", { silent = true })
vim.keymap.set("n", "<leader>s", ":SupermavenToggle<CR>", { silent = true })
vim.keymap.set("n", "<leader>d", ":ToggleInlineDiagnostics<CR>", { silent = true })

-- editing
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<S-down>", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "<S-up>", ":m '<-2<CR>gv=gv")
vim.keymap.set("v", "<S-left>", "<gv")
vim.keymap.set("v", "<S-right>", ">gv")
vim.keymap.set({ "n", "v" }, "c", '"_c')
vim.keymap.set({ "n", "v" }, "C", '"_C')
vim.keymap.set("v", "p", "P")
vim.keymap.set("n", "<leader>F", function()
  require("conform").format()
end)
vim.keymap.set("n", "<leader>f", "<cmd>ToggleConform<CR>", { desc = "Toggle autoformatting", silent = true })

-- windows
vim.keymap.set({ "n", "v", "i" }, "<c-v>", ":vsplit<CR>")
vim.keymap.set({ "n", "v", "i" }, "<c-down>", ":NavigatorDown<CR>")
vim.keymap.set({ "n", "v", "i" }, "<c-up>", ":NavigatorUp<CR>")
vim.keymap.set({ "n", "v", "i" }, "<c-right>", ":NavigatorRight<CR>")
vim.keymap.set({ "n", "v", "i" }, "<c-left>", ":NavigatorLeft<CR>")

vim.keymap.set("n", "<leader>bo", ":%bd|e#|bd#<CR>", { silent = true }) -- close all buffers but the current one
vim.keymap.set({ "n", "v", "i" }, "<C-x>", ":bd<CR>", { silent = true })
vim.keymap.set("n", "<leader>by", ":%y<CR>")
vim.keymap.set("n", "<leader>bY", ":let @+ = expand('%:p')", { silent = true })
-- vim.keymap.set("n", "<S-Tab>", ":bprevious<CR>", { silent = true })
-- vim.keymap.set("n", "<Tab>", ":bnext<CR>", { silent = true })
-- vim.keymap.set("n", "<C-S-Tab>", ":bprevious<CR>", { silent = true })
vim.keymap.set("n", "<Esc>", ":noh<CR>", { silent = true })

vim.keymap.set("n", "<leader>gg", ":LazyGit<CR>")

vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "<Down>", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("n", "<Up>", "gk")
vim.keymap.set("n", "<leader>m", ":TSJToggle<CR>", { silent = true })
